const ROLES = {
  EMPLOYEE: 'EMPLOYEE',
  HR_MANAGER: 'HR_MANAGER',
  HR_PAYROLL_USER: 'HR_PAYROLL_USER',
  HR_PAYROLL_MANAGER: 'HR_PAYROLL_MANAGER',
  ADMIN: 'ADMIN',
};

const CONTRACT_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  ARCHIVED: 'ARCHIVED',
};

const REQUEST_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REFUSED: 'REFUSED',
};

const RULE_CATEGORY = {
  BASIC: 'BASIC',
  ALLOWANCE: 'ALLOWANCE',
  GROSS: 'GROSS',
  DEDUCTION: 'DEDUCTION',
  NET: 'NET',
};

const COMPUTATION_TYPE = {
  FIXED: 'FIXED',
  PERCENTAGE: 'PERCENTAGE',
  FORMULA: 'FORMULA',
};

const PAYRUN_STATUS = {
  DRAFT: 'DRAFT',
  COMPUTED: 'COMPUTED',
  VALIDATED: 'VALIDATED',
  PAID: 'PAID',
};

const TIME_UNIT = {
  DAYS: 'DAYS',
  HOURS: 'HOURS',
};

const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
};

module.exports = {
  ROLES,
  CONTRACT_STATUS,
  REQUEST_STATUS,
  RULE_CATEGORY,
  COMPUTATION_TYPE,
  PAYRUN_STATUS,
  TIME_UNIT,
  PAGINATION,
};
